<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>omnitest</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../src/Omni.csproj" />
  </ItemGroup>
</Project>
