"""voxgig_omni - shared multi-language test runner."""

from .runner import (
    EXISTSMARK,
    NULLMARK,
    UNDEFMARK,
    OmniError,
    errify,
    fixjson,
    loadspec,
    makeRunner,
    match,
    matchval,
    nullmodifier,
    resolvespec,
)
from .util import (
    ABSENT,
    clone,
    deepequal,
    getpath,
    islist,
    ismap,
    isnode,
    jsonstr,
    pathify,
    stringify,
    walk,
)

__all__ = [
    'ABSENT',
    'EXISTSMARK',
    'NULLMARK',
    'UNDEFMARK',
    'OmniError',
    'clone',
    'deepequal',
    'errify',
    'fixjson',
    'getpath',
    'islist',
    'ismap',
    'isnode',
    'jsonstr',
    'loadspec',
    'makeRunner',
    'match',
    'matchval',
    'nullmodifier',
    'pathify',
    'resolvespec',
    'stringify',
    'walk',
]
